[project]
name = "auto-reply-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "omerkhanlhr", email = "omar.championcr@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "google-genai>=2.24.0",
    "pyautogui>=0.9.54",
    "python-dotenv>=1.2.3",
]

[project.scripts]
auto-reply-bot = "auto_reply_bot:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
